export class Paymentinformation {
    
    //generated
    id: number;

    // set from request
    taskerId: number;
    seekerId: number; //optional
    reqTrackingId: string;

    //set on client side
    paymentConfirmationNo: string;
	paymentAmount: number;
    paymentMethod: string;
    
    //generated by server
    paymentReportDate: Date
}
